### ISSUE TITLE
Connectivity?

### ISSUE THREAD

**Issue by r3m0t** [microsoft/vscode-data-wrangler#12]
Hi, can you clarify what data is sent to Microsoft servers, as the privacy statement is very generic.

In particular, I notice a natural language option in the README, are these prompts sent and/or stored?

**Comment by pwang347** [comment]
Hi @r3m0t, thanks for opening this issue!

Just wanted to clarify that the reference to natural language was added erroneously and has been since removed. Note that for the current iteration of Data Wrangler we do not support any natural language capabilities.

In general, our policy is to **never** send telemetry for anything potentially containing customer information, whether it's the dataset, code or local filesystem paths (or in this case, generic user input in the form of a prompt which may or may not contain sensitive information).

Things that we will log typically includes operation parameter information unrelated to the dataset itself (e.g. we might include the number of selected columns for an operation, but never the column name or data). We also might log things like how many lines of code were used for a custom operation, whether certain options were included, etc.

We will also be adding a more detailed document in the upcoming releases with more information, so do stay tuned for that! 

Thank you for trying Data Wrangler!

**Comment by pwang347** [comment]
Closing for now, but feel free to re-open if you have any further follow-ups
