### ISSUE TITLE
Data Wrangler cannot be opened from interactive window

### ISSUE THREAD

**Issue by jabbera** [microsoft/vscode-data-wrangler#140]
## Environment data

-   VS Code version: 1.86.2
-   Data Wrangler Extension version (available under the Extensions sidebar): 0.26.0
-   Jupyter Extension version (available under the Extensions sidebar): 2024.1.1
-   Python Extension version (available under the Extensions sidebar): 2024.0.1
-   OS (Windows | Mac | Linux distro) and version: Windows/WSL2 Ubuntu
-   Pandas version: 2.2.1
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour

from a jupytext file:

# %%

df.head()

execute in interactive window. 

Button to open wrangler appears

## Actual behaviour

No button to open the wrangler appears

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

# %%

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))

df.head()

![image](https://github.com/microsoft/vscode-data-wrangler/assets/301208/4b27d7a8-cc49-4d92-936d-c876dbc7029e)

Note: This was previously closed here as not working dependent on a jupyter feature: https://github.com/microsoft/vscode-data-wrangler/issues/88

The maintainer of the Jupyter extension said this isn't an issue and should be re-opened here: https://github.com/microsoft/vscode-jupyter/issues/15196#issuecomment-1958376293

**Comment by ntaylor-ads** [comment]
Bump. This is the feature I require.

**Comment by pwang347** [comment]
@jabbera @ntaylor-ads @yinghawl

Hi all! Thanks for opening this request.

Note that https://github.com/microsoft/vscode-jupyter/issues/15196 is required for code export back to the original Python file. We consider this to be a core scenario for users who want to load their variable, perform transformations on it and then be able to get the code back in the right spot so that it can be executed.

That being said, we are open to feedback if folks are interested in being able to enter DW _even_ if the export back to file option is disabled while we wait for the API in Jupyter to settle.

**Feedback point 1**: Could you please share more about what you would like to achieve with Data Wrangler in the interactive window? For example, do you expect to be mostly performing some quick explorations (ie. only viewing the data and not coding), or perhaps you'd like to move from the Python file to code in DW and keep the code? It would be great to learn more about your workflow.

**Feedback point 2**: What would be your ideal way to enter Data Wrangler from the interactive window? One immediate difference I can think of here is that the cell status bar is collapsed by default in an interactive window, so we might need something else.

We can't promise that we'd be able to satisfy everyone here as there are probably very different workflows, but understanding this more would definitely help guide our approach to addressing your feedback.

Thanks!

**Comment by yinghawl** [comment]
For my use case, I mostly use it for exploratory analysis, rather than relying on it to generate codes. Right now to look at data I would have to export it to an excel sheet. I can see that this will make it more efficient in doing adhoc analysis on the data as someone is building data pipeline in Python. With that being said, I’d vote for disable the ability to export code to Python while waiting on the api on Jupyter to settle.

**Comment by pwang347** [comment]
@jabbera @ntaylor-ads @yinghawl @williamchiu-nmic @mix060514
Hey all! Just an update that we've enabled the interactive window entrypoint on both the latest stable/pre-release channels as long as you are running the latest Jupyter pre-release (2024.3.2024030101)!

Notes:
* This is currently only available on VS Code Insiders as the latest Jupyter extension pre-release is only available there, but is expected to reach regular VS Code in April.
* The entrypoint is currently the Jupyter variables panel, ie.
![image](https://github.com/microsoft/vscode-data-wrangler/assets/8560030/968d5c4d-d43e-49e8-b3cb-ff1157726cc2)
* As discussed above, there is currently no way to export code back to the original Python file for now, but we will continue tracking that issue in the Jupyter repo.
* We plan to add support for more entrypoints for interactive window and will continue to monitor feedback related to this.

Thanks again for contributing to the discussion!

**Comment by VelkoKamenovAF** [comment]
Enabling the entrypoint for the interactive window is a great feature. The problem I am facing is that in order to use it I have to initially open "manually" the data wrangler through an existing csv/parquet file for example and the entry point activates after that for all data frames loaded in the interactive cession. But starting the data wrangler through the entrypoint is not possible without this initial step of opening it manually.

**Comment by pwang347** [comment]
> Enabling the entrypoint for the interactive window is a great feature. The problem I am facing is that in order to use it I have to initially open "manually" the data wrangler through an existing csv/parquet file for example and the entry point activates after that for all data frames loaded in the interactive cession. But starting the data wrangler through the entrypoint is not possible without this initial step of opening it manually.

Hi @VelkoKamenovAF, thanks for letting me know! The issue is now fixed and released in our latest version. Cheers!
