### ISSUE TITLE
Insight calculations takes forever and stops jupyter kernel

### ISSUE THREAD

**Issue by veonua** [microsoft/vscode-data-wrangler#167]
Insights on large data frames 1M+ rows take too long, it's not possible to use the Jupyter kernel while it's calculating.

Firstly, it'd help to set a time limit on insight calculations, like stopping after a few minutes. Right now, when DataWrangler tries to analyze a large dataset, I end up having to force-close the kernel and remind myself not to use it with that specific DataFrame. This inconvenience outweighs just seeing a "Failed to load data" message.

It'd be great if the plugin could let us turn insights on or off for each column, or just skip insights for numpy arrays altogether. Most of the time, insights on numpy arrays aren't really useful anyway.

Diagnostic data
Jupyter extension version: 2024.2.2024022602
Python extension version: 2024.2.1
.NET Install Tool for Extension Authors extension version: 2.0.3
Python package dependencies:
{
  "installed": {
    "pandas": "1.5.3",
    "pyarrow": "15.0.1"
  },
  "required": {
    "pandas": "0.25.2"
  },
  "unsatisfied": []
}
Extension version: 0.28.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22621

## Expected behaviour

Insights calculations are fast or fail fast

## Actual behaviour

Insights makes attempt to process all columns and on embeddings (large numpy array) column it stops for many minutes

related to https://github.com/microsoft/vscode-data-wrangler/issues/159

**Comment by kycutler** [comment]
Hi @veonua, thanks for opening this issue!

This has been tricky to fix -- usually, Data Wrangler will interrupt any in-progress calculations such as column insights when another action is performed, so you should never be blocked. However, since numpy arrays are implemented in C/C++, the calculation runs completely in native code and so can't be interrupted. This happens in notebooks as well -- you can try running `df["column"].value_counts()` to see this behavior.

That said, we have now implemented a workaround to allow the calculation to be interrupted, as well as greatly improving the performance for numpy arrays and some other data types. The fix is available in the latest pre-release version of Data Wrangler, which you can install by selecting "Switch to Pre-Release Version" from the extension page in VS Code.

Closing this issue for now, but please feel free to re-open it if the experience is still not workable.

Thanks for trying Data Wrangler!
