### ISSUE TITLE
loading taking too long

### ISSUE THREAD

**Issue by LubasiEmpirica** [microsoft/vscode-data-wrangler#209]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2024.5.0
-   Python extension version: 2024.8.1
-   .NET Install Tool for Extension Authors extension version: 2.0.6
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.1.4",
    "pyarrow": "14.0.2",
    "openpyxl": "3.0.10"
  },
  "required": {
    "pandas": "0.25.2",
    "openpyxl": "0.0.1"
  },
  "unsatisfied": []
}
```

-   Entrypoint: Reopen
-   Active mode: dataWrangler

Extension version: 1.2.1
VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.85GB (5.01GB free)|
|Process Argv|D:\\Nkalolang\\Downloads\\in_force_file_extract_20240601.xlsx --crash-reporter-id ba62b30f-13a8-4cdd-910c-5e36cbbaa5d2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870

```

</details>

**Comment by pwang347** [comment]
Hi @LubasiEmpirica, thanks for opening this issue! Could you please share a GIF of the slowness you are seeing or if possible the dataset you are using that is slow if it is not confidential?

**Comment by friachi** [comment]
I am facing same issue, I beleive it is related to the pandas underlying the data wrangler (at least in my case) because I did compare load time on same dataset using 'direct python pandas code' vs 'data wrangler' both reading from parquet, and they are almost similar in performance in my case.

I continued my test using this time duckdb and it was 14 folds faster to wrangle

I was wondering if the team can consider switching to duckdb or even Polars instead of pandas, would that help?

**Comment by pwang347** [comment]
Hi @friachi, thank you for the investigation and sharing your findings! As you called out, in some areas Pandas is the main bottleneck for performance. Hence we do have plans on our backlog to investigate supporting engines other than Pandas, hope this helps!

@LubasiEmpirica  Will close this issue due to inactivity, but please feel free to reopen if you get the chance to provide more details!
