### ISSUE TITLE
Add horizontal scrolling shortcut using ctrl+shift

### ISSUE THREAD

**Issue by Detectronic-AH** [microsoft/vscode-data-wrangler#233]
There is currently no other way to scroll horizontally than to use the horizontal bar along the bottom of the window.

It would be great to have a shortcut to scroll horizontally like what exists in apps like Excel and Google Sheets.

**Comment by pwang347** [comment]
Hi @Detectronic-AH, thank you for opening this issue!

It should be possible already to scroll horizontally with these options:
- Shift + Mouse wheel (scrolling)
- Left and Right arrow keys (move by cell)
- Fn + Left and Right arrow keys (move to grid horizontal start / end)
- Home and End (move to grid horizontal start / end)

Could you please check to see if the above work for you?
Thanks!

**Comment by Detectronic-AH** [comment]
Hi @pwang347, all of the above work.

I could not see these key-bindings documented anywhere, nor are they in the keyboard shortcuts section in vscode. Are there any plans in the future to allow for these shortcuts to be remapped?

Thanks!

**Comment by pwang347** [comment]
@Detectronic-AH thanks for confirming! These are actually all built-in browser shortcuts (except the left/right arrow, which is specific to the grid we use), so unfortunately this means that we won't be able to add remaps for these in VS Code.

That said, we do have plans in the future to add more keyboard shortcuts using the VS Code framework for improved keyboard productivity and these will all be remappable.

Will close the issue now since the horizontal scroll shortcut exists. Hope this helps!
