### ISSUE TITLE
No open data wrangler button in vscode notebooks

### ISSUE THREAD

**Issue by venturozzaccio** [microsoft/vscode-data-wrangler#25]
Environment data

-   VS Code version 1.77
-   Data Wrangler Extension version (available under the Extensions sidebar): both release and pre release
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): 3.10
-   OS (Windows | Mac | Linux distro) and version: ubuntu 22.04 wsl
-   Pandas version: 1.5.3
-   Python and/or Anaconda version: conda 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Expected behaviour

Button to appear after df.head() of a PD df

## Actual behaviour

No button in vscode notebooks, opeining csv files directly works

**Comment by venturozzaccio** [comment]
It actually works on non insider version

**Comment by pwang347** [comment]
Hi @venturozzaccio! I suspect that the issue is due to the fact that the latest [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) release with version `v2023.4.1000951011` is targeting insider 1.78.0, and it looks like you were on 1.77. It's possible that there could have been some error on automatic upgrading.

If you want to try using Insiders again, I would recommend trying to update VS Code from the help menu, installing the latest pre-release Jupyter extension and trying again
![image](https://user-images.githubusercontent.com/8560030/229643586-6206be0f-c725-4a73-a477-9e07c4145c8c.png)

Thanks for trying Data Wrangler!

**Comment by pwang347** [comment]
Hi @BabakAmini, I'm glad you were able to resolve the issue!

Interestingly, I don't believe there were any related changes in 0.11.0. **If possible, could you please confirm that reverting to 0.9.1 causes the button to disappear again?**

I tried your setup above and could not repro the issue, so I am wondering if it could be possibly a temporary installation issue from VS Code itself.

We are close to releasing stable version 0.10.0, and will update the changelog associated with that version.

Cheers!
