### ISSUE TITLE
DW crashes after single use, and you have to fully refresh vs code to work again

### ISSUE THREAD

**Issue by droy-proxsys** [microsoft/vscode-data-wrangler#275]
Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22635

-   VS Code version: v1.8.0
as for other versions applies to all current versions - i reinstalled everything from scratch and it still does it.

## Expected behaviour

debugging -> view df -> it works -> stop code and restart code -> view df -> it works

## Actual behaviour

debugging -> view df -> it works -> stop code and restart code -> view df -> crashes (you have to fully refresh vscode do get it to work again!
![image](https://github.com/user-attachments/assets/9e88b0c3-28f5-41ca-911d-88040f4b1e1e)

## Steps to reproduce:

debugging -> view df -> it works -> stop code and restart code -> view df -> crashes

Update i have noticed when i end one usage of the viewer and before i restart with the viewer still open it throws 
![image](https://github.com/user-attachments/assets/d64e4a4d-bd25-4815-988e-3f9c088ffd84)

that may be a part of the cause and why it takes a full restart.

**Comment by pwang347** [comment]
Hey @droy-proxsys, sorry to hear that you're running into issues.

Could you please try the following?
1. Try to trigger this error again: 
![image](https://github.com/user-attachments/assets/6963f507-1022-430d-a8e6-7fdce8b554c1)

2. Open the developer console
<img width="370" alt="image" src="https://github.com/user-attachments/assets/1ffe19ec-5ebf-4f84-8f4a-e22882548ff2">
<img width="259" alt="image" src="https://github.com/user-attachments/assets/91558df1-80cf-473c-ab6b-da6fc099bd1f">

3. Copy the entire error message that appears (the error below is just an example, but it would be good to get the whole stacktrace)
<img width="697" alt="image" src="https://github.com/user-attachments/assets/1162991c-e986-45cd-9433-01002b81bde9">

For this message:
![image](https://github.com/user-attachments/assets/73092e60-0412-42c9-9ab0-b5bb8c5de139)

It's currently expected since the viewer will not be able to access the variable anymore when the debug session closes.

Thanks!

**Comment by pwang347** [comment]
Hi @droy-proxsys, thank you for the extra info! After digging around, I'm quite confident that I've figured out what the problem is, but would be good for you to give it a try to confirm.

I've uploaded a build here: https://file.io/tZPtTHbwj12e (apologies, I couldn't upload to GitHub directly since the file is a bit too big).

To install the VSIX file directly, you can run this command:
<img width="617" alt="image" src="https://github.com/user-attachments/assets/58f8de26-b4fb-4160-a4b5-af78a8ad26c8">

If you can confirm that this resolves this issue for you, I will merge it and add the change to the next pre-release version!

--

Also, if the above works for you, I'm curious to know what your debugpy setup is. Did you have any custom/manual installation steps, or did you just install the VS Code Python extension? It seems like VS Code APIs might be behaving differently for your setup.

**Comment by droy-proxsys** [comment]
[vscode-app-1725662208153.log](https://github.com/user-attachments/files/16913451/vscode-app-1725662208153.log)


negative. same issue, no change. 

i just use default debugpy. nothing special set up on it... too lazy... lol

**Comment by pwang347** [comment]
@droy-proxsys Hmm, and just to confirm do you now see a button with "View logs" like this in the error message?
<img width="458" alt="image" src="https://github.com/user-attachments/assets/a145b8e8-6edf-4d17-a5e3-a8cc24665bf0">
(I just added this, so if it's not appearing then VS Code might be forcing you onto the marketplace version)

You can also check from the extension page (it should be 0.0.0-dev, and you might need to temporarily disable automatic updates)
![image](https://github.com/user-attachments/assets/d8d60cab-47c2-40ee-b888-bf62ae3f3b49)

**Comment by droy-proxsys** [comment]
I can confirm it was 0.0.0 and no and you cannot see a log button

![image](https://github.com/user-attachments/assets/38142b07-9b27-412b-9318-e6607c635312)

when i got to the output and look at datawrangler there is nothing, when i look at the one labeled as my df name, I can see py code and print outs of the data.

**Comment by pwang347** [comment]
Hmm that's weird, if you don't see the button that means you don't have the change (unless I shared the wrong build). Just in case, I've re-uploaded it here: https://github.com/pwang347/file-dump/blob/main/ms-toolsai-data-wrangler-insiders.vsix

Could you please install this one, reload, and give it another try? This one should also have a message "@@TEST" at the start of the console log, just to indicate that it's the right version.

<img width="450" alt="image" src="https://github.com/user-attachments/assets/d195f922-475e-4fc2-b672-43eff00a79ea">

If you don't see the message above, please double-check again that the extension page looks exactly like this (and it's not asking you to refresh extensions or anything else):
![image](https://github.com/user-attachments/assets/1ae8d59c-4cf6-413f-adda-eb418a6e4b6d)

Thanks again!

**Comment by droy-proxsys** [comment]
![image](https://github.com/user-attachments/assets/722c6c11-82cb-41eb-a9da-099707889ea6)
![image](https://github.com/user-attachments/assets/6ce53cec-ef69-4034-b7f4-aea89ed2f799)
![image](https://github.com/user-attachments/assets/11318f4c-d6e1-484e-8493-5160135b7312)
![image](https://github.com/user-attachments/assets/306fe4d1-a9fb-492d-ba87-7b378fb8d510)
[vscode-app-1725790688136.log](https://github.com/user-attachments/files/16921810/vscode-app-1725790688136.log)


I'm using dev, auto update is off, your log button does not show, the program still fails. @@TEST does show up in logs...

**Comment by pwang347** [comment]
Hmm okay, at least it looks like it is indeed the error I think it is:
![image](https://github.com/user-attachments/assets/78271e3a-a085-4dc6-ab33-0a5f349cd22e)

Could you please give this one a try?
https://github.com/pwang347/file-dump/blob/main/ms-toolsai-data-wrangler-insiders.vsix

You should now see `@@TEST2` and a few more logs prefixed with @@.

**Comment by droy-proxsys** [comment]
[vscode-app-1725899007872.log](https://github.com/user-attachments/files/16933446/vscode-app-1725899007872.log)

Logs attached, but everything worked this time. I think the logs show 3 loops over it or so.

**Comment by pwang347** [comment]
@droy-proxsys Great, thanks for confirming! We'll add these changes and let you know when it's available.

Looking at the log, it seems like for some reason VS Code's debug adapter tracker is killing your old debug session after a new one (which it creates with the same ID) is created. So you have two debug sessions active simultaneously with the same ID, which we weren't expecting.

```
console.ts:137 [Extension Host] @@DEBUG CREATED 22c35358-3204-4b4c-a6d5-0e75a10882fb
console.ts:137 [Extension Host] @@DEBUG ON WILL START 22c35358-3204-4b4c-a6d5-0e75a10882fb
console.ts:137 [Extension Host] @@DEBUG ON EXIT 22c35358-3204-4b4c-a6d5-0e75a10882fb
```

Possibly related to this error that keeps showing up:
`Error: Trying to add a disposable to a DisposableMap that has already been disposed of. The added object will be leaked!`.
