### ISSUE TITLE
Pandas v1.1.0 doesn't allow to use DataWrngler?

### ISSUE THREAD

**Issue by JoaoCastro99** [microsoft/vscode-data-wrangler#313]

**Comment by pwang347** [comment]
Hi @JoaoCastro99, thanks for opening this issue!
That is correct. Starting from version 1.6.0 of Data Wrangler we have increased our minimum supported version from 0.25.4 to 1.2.0. If you are not able to upgrade your Pandas version, please consider using an older version of Data Wrangler.

Will close the issue now as this is intentional, but please feel free to reopen if you have any more questions.

**Comment by JoaoCastro99** [comment]
Hi @pwang347 . Been trying to downgrade the Data Wrangler several times but I cannot find a way to get a version compatible with pandas 1.1.0. Could you please point me to the version I should be using for this pandas version? Unfortunately I cannot do it other way around since I can't upgrade pandas version either.

**Comment by pwang347** [comment]
Hi @JoaoCastro99, got it - could you please try v1.4.2 or lower?
