### ISSUE TITLE
Can't open datawrangler from debug variable view

### ISSUE THREAD

**Issue by fnimft** [microsoft/vscode-data-wrangler#322]
## Environment data

-   VS Code version: 1.94.2
-   Data Wrangler Extension version (available under the Extensions sidebar): v1.13.0
-   Jupyter Extension version (available under the Extensions sidebar): 2024.10.2024100401.
-   Python Extension version (available under the Extensions sidebar): 2024.16.1.
-   OS (Windows | Mac | Linux distro) and version: win32 (x64).
-   Pandas version:  2.2
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX

## Expected behaviour

Data wrangler window to open

## Actual behaviour
![Image](https://github.com/user-attachments/assets/e67df882-d27e-4421-a681-3caf415cd99a)
![Image](https://github.com/user-attachments/assets/a5e9a308-1a50-4c68-ba8e-2fbdb6711b46)

![Image](https://github.com/user-attachments/assets/c6a15060-6ab5-4863-853b-5de3d4080fb0)
![Image](https://github.com/user-attachments/assets/43910ff8-abea-4a78-8f77-e71b9b373bd1)
![Image](https://github.com/user-attachments/assets/9553ddc6-68f6-4361-9a31-22c9f5c852c5)
printet in debug terminal:  {"type": "pandas", "supportedEngines": ["pandas"]}

## Steps to reproduce:
![Image](https://github.com/user-attachments/assets/11d5eea7-2332-4e87-9e0b-50560e8fadaa)

Can get the datawrangler windows to open in a minimum example ( python file, define df, open in data wrangler). Most other instances it fails, especially in prefect flows/tasks. 

## Logs

<details>
<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
printet in debug terminal:  {"type": "pandas", "supportedEngines": ["pandas"]}

```
</p>

<p>

```
11:35:39.308 [debug] Evaluating in debugger : 09216e45-430d-4d1e-908e-986251557c3d: _VSCODE_getVariable("info", True, df)
11:35:39.346 [info] Showing data viewer with command dataWrangler.launchDataViewer for variable {"name":"df","type":"DataFrame","count":10,"shape":"(10, 5)","size":0,"supportsDataExplorer":false,"value":"...","truncated":false,"frameId":223,"fullType":"pandas.core.frame.DataFrame"}
</p>
</details>
[vscode-app-1729852213619.log](https://github.com/user-attachments/files/17520649/vscode-app-1729852213619.log)

**Comment by pwang347** [comment]
Hi @fnimft, thank you for opening this issue and we are sorry that you are experiencing this. Would you by any chance have a minimal code sample to trigger this error, since you mention that it works in the simple case but not in others?

For example, I've tried using the same extension and pandas versions and the following snippet taken from [prefect docs](https://docs-3.prefect.io/3.0/get-started/index) is working for me, I can launch the variable `li`:
![Image](https://github.com/user-attachments/assets/42c1de8b-f566-49c0-ae14-b900d64cbee5)

And just to make sure I understood, in the debug console, you see the text `{"type": "pandas", "supportedEngines": ["pandas"]}`?
![Image](https://github.com/user-attachments/assets/e6918e8d-7618-4e09-b8f2-ce6c4d965b2f)

If that is the case, then it seems like the debugger may be ignoring Data Wrangler's request and dumping the output we need into the console. Could you please share also your [Python debugger extension](https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy) version, and if you have any custom Python debugger configurations?

**Comment by fnimft** [comment]
Thanks for the swift reply @pwang347. 

The debug console where {"type": "pandas", "supportedEngines": ["pandas"]} is printed, im referring to the terminal window that is opened when a debug session i started. ![Image](https://github.com/user-attachments/assets/fbb52b7a-7e11-48e4-a713-e63f48a0df2a).

I have created a minimal code sample that triggers the issue for me:
I have two files:

- test.py
- flows/test2.py

with the following code
 
```
from functools import partial

from prefect.testing.utilities import prefect_test_harness

from flows.test2 import hello_universe


def run_stuff():
    run_func = partial(hello_universe, names=['Marvin', 'Trillian', 'Ford'])
    with prefect_test_harness():
       run_func()

if __name__ == "__main__":
    run_stuff()
```

and 

```
import pandas as pd
from prefect import flow, task


@task(log_prints=True)
def say_hello(name: str):
    print(f"Hello, {name}!")

@flow(validate_parameters=False, log_prints=True)
def hello_universe(names: list[str]):
    mock_df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
    for name in names:
        say_hello(name)
```
Now inspecting mock_df from the debug variables gives the following errors:

![Image](https://github.com/user-attachments/assets/25ca4876-0553-4808-8621-0ce7048f0bd1)

Error text: 
![Image](https://github.com/user-attachments/assets/10beadef-f8fa-4bdb-b857-52a602628aa6)
.  


This is my vscode launch.json config:

```
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "cwd": "${workspaceFolder}",
            "console": "integratedTerminal",
            "justMyCode": false,
            "env": {"PYTHONPATH": "${workspaceFolder}"},
            "exceptionOptions": [
                {
                    "path": [
                        {
                            "names": [
                                "Python Exceptions"
                            ]
                        }
                    ],
                    "breakMode": "always"
                }
            ] 
        
        },
        {
            "name": "Debug Unit Test",
            "type": "debugpy",
            "request": "launch",
            "justMyCode": false,
        },
    ]
}
```
and debugger extension is version v2024.12.0.

**Comment by pwang347** [comment]
Hi @fnimft, thank you very much for the repro and extra information! I was able to recreate the issue. It seems like the culprit here is actually `@flow(validate_parameters=False, log_prints=True)`. Specifically, `log_prints=True` breaks our communication mechanism since we currently leverage STDOUT to handle the communication from the debugger session scope.

The workaround for now is to disable the output capturing mechanism here while you are debugging (or anything else that captures output in that debug context). If you are interested in having DW add support for such a scenario (ie., being able to launch while outputs are being captured), please feel free to open a separate feature request for us to investigate more.

Thanks!
