### ISSUE TITLE
Conflict with Positron's Data Functionality

### ISSUE THREAD

**Issue by GorunNova** [microsoft/vscode-data-wrangler#327]
Type: <b>Bug</b>

After installing this plugin in VSCode, the Data tab in Positron no longer displays any data. Even after uninstalling the plugin from VSCode, the display issue persists.

Extension version: 1.12.1
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.70GB (3.67GB free)|
|Process Argv|--crash-reporter-id 2f60ae41-093e-4294-8130-38261f796536|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by pwang347** [comment]
Hi @GorunNova, thanks for opening this issue!

If I understood correctly, you have both VS Code and Positron installed. After installing Data Wrangler in VS Code it corrupted your Positron installation?

Our extension isn't really doing anything particularly different from other VS Code extensions, so it seems like this may be an issue on the Positron side (e.g., if it has some sort of interaction with our extension specifically, since I see that it doesn't show up in the Positron marketplace).

Assuming your Positron is pointing to the same extensions folder as your VS Code somehow, you can try running this command (open with Ctrl+Shift+P):
![Image](https://github.com/user-attachments/assets/7c178c54-667d-4b71-9955-ce602a07fd79)

And make sure that after uninstalling the Data Wrangler extension folder was deleted. Sometimes extensions are cached there.

**Comment by pwang347** [comment]
Will close this issue for now as it seems unrelated, but hopefully the steps above help!
