### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 39: invalid start byte

### ISSUE THREAD

**Issue by salahelfarissi** [microsoft/vscode-data-wrangler#42]
## Environment data

-   VS Code version: 1.78.2
-   Data Wrangler Extension version (available under the Extensions sidebar): 0.8.0
-   OS (Windows | Mac | Linux distro) and version: XXX

## Expected behaviour

I downloaded a csv file from IGN website [WFS services](https://geoservices.ign.fr/documentation/services). I expected to be able to open the CSV with Data Wrangler.

## Actual behaviour

I got the following error upon opening the file: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 39: invalid start byte`

**Comment by pwang347** [comment]
Hi @salahelfarissi, thank you for trying Data Wrangler!
Currently, we don't present options to customize the CSV import step but it's something that is on our roadmap.

As a temporary workaround, you can write the following code in an IPYNB file to launch Data Wrangler:
```
import pandas as pd
df = pd.read_csv("Ressources_de_services_web_2023-05-02.csv", encoding="windows-1252", on_bad_lines='skip')
df
```

It looks like `encoding` is needed because of this special character ® on line 242 (and others).
`on_bad_lines` is needed because there's an extra column in line 170.

**Comment by salahelfarissi** [comment]
Thanks. It worked.
Great extension.
