### ISSUE TITLE
Promote Data Wrangler when looking for csv file handlers

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-data-wrangler#92]
When you run a vanilla installation of VS Code without extensions and you try to open csv file it proposes extensions to handle the filetype, but we cannot find Data Wrangler in the first results, we should rank Data Wrangler higher.

## Environment data

Mac
Version: 1.82.0
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:08:29.670Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

## Expected behaviour

Data Wrangler should be the top or one of the top results

## Actual behaviour

Data Wrangler is not shown in the top 10 extensions to open csv files. I suppose because it has less installs.

## Steps to reproduce:

1. Run a new instance of VS Code (without any extensions).
2. Open extensions and search `ext:csv` for extensions to handle csv files

You will see something like this (No Data Wrangler visible in the results):
<img width="1271" alt="Screenshot 2023-09-11 at 10 17 27" src="https://github.com/microsoft/vscode-data-wrangler/assets/79476/25eb210a-0cd1-4e1f-a477-02f4d53ef33d">

**Comment by iemejia** [comment]
If we cannot rank it better we should at least recommend it as we do already for other extensions.

<img width="1552" alt="Screenshot 2023-09-11 at 10 33 26" src="https://github.com/microsoft/vscode-data-wrangler/assets/79476/16fbb8eb-079d-47b3-9f59-b8e4eb2ac9b4">

**Comment by pwang347** [comment]
Hey @iemejia, thanks for the feedback!

Please note that we should already be appearing in the list for CSV files, but as you've called out we don't appear in the first page due to the install count. So unfortunately there's not much we can do about that.

Regarding recommendations, starting on the upcoming stable release of VS Code Jupyter users will be recommended the Data Wrangler extension.

Cheers!
